### ISSUE TITLE
Баланс счета to (savingAccount) при переводе не увеличивается на сумму amount в методе transfer класса Bank

### ISSUE THREAD

**Issue by TatyanaKonysheva** [Mlle1Maniaque/Javaqa-team-diplom#19]
# Описание
Баланс счета `to` (`savingAccount`) не увеличивается на сумму `amount` при переводе в методе `transfer` класса `Bank`.

# Локация дефекта
https://github.com/Mlle1Maniaque/Javaqa-team-diplom/blob/9f1ae61a08097f4d0444ff2fe3b650c3434f199e/src/main/java/ru/netology/javaqadiplom/Bank.java#L16

# Шаги воспроизведения 
 1. Открыть [код программы](https://github.com/Mlle1Maniaque/Javaqa-team-diplom/tree/main) в IDEA
 2.  Запустить тест `shouldTransferPositiveAmountToCreditAccount` с помощью `mvn clean verify` с переменными для `creditAccount`:
     `initialBalance`=1000,
     `creditLimit`= 5000,
     `rate`=15;
с переменными для `savingAccount`:
     `initialBalance`=5000,
     `minBalance`= 500,
     `maxBalance`=15000,
     `rate`=15
и суммой `amount` = 1000.
 3. Просмотреть на вывод в консоли
 
*Ожидаемый результат:* успешное выполнение теста.  `balance` = 2000, увеличивается на сумму `amount`.
*Фактический результат:* тест не проходит. savingAccount.getBalance() = 1000.
*Тест:* 
https://github.com/Mlle1Maniaque/Javaqa-team-diplom/blob/9f1ae61a08097f4d0444ff2fe3b650c3434f199e/src/test/java/ru/netology/javaqadiplom/BankTest.java#L92

# Скриншот

![image](https://github.com/Mlle1Maniaque/Javaqa-team-diplom/assets/127970375/4e418021-3ef5-4a37-b4a3-124e6e0f39f2)

#  Логи сборки

<details>
<summary>mvn clean verify</summary>

'''txt
[ERROR] Tests run: 8, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.143 s <<< FAILURE! - in ru.netology.javaqadiplom.BankTest
[ERROR] shouldTransferPositiveAmountToCreditAccount  Time elapsed: 0.116 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2000> but was: <1000>
	at ru.netology.javaqadiplom.BankTest.shouldTransferPositiveAmountToCreditAccount(BankTest.java:107)

[ERROR] shouldTransferAmountMinBalance  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <5500> but was: <1000>
	at ru.netology.javaqadiplom.BankTest.shouldTransferAmountMinBalance(BankTest.java:167)

[ERROR] shouldTransferToSavingAccountMaxCreditLimit  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <8000> but was: <5000>
	at ru.netology.javaqadiplom.BankTest.shouldTransferToSavingAccountMaxCreditLimit(BankTest.java:87)

[ERROR] shouldTransferToSavingAccountOverCreditLimit  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <10000> but was: <3000>
	at ru.netology.javaqadiplom.BankTest.shouldTransferToSavingAccountOverCreditLimit(BankTest.java:67)

[ERROR] transferPositiveAmountToSavingAccount  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <3000> but was: <-1000>
	at ru.netology.javaqadiplom.BankTest.transferPositiveAmountToSavingAccount(BankTest.java:26)

[ERROR] shouldTransferAmountOverMinBalance  Time elapsed: 0.003 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <5000> but was: <-200>
	at ru.netology.javaqadiplom.BankTest.shouldTransferAmountOverMinBalance(BankTest.java:148)

[INFO] Running ru.netology.javaqadiplom.CreditAccountTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in ru.netology.javaqadiplom.CreditAccountTest
[INFO] Running ru.netology.javaqadiplom.SavingAccountTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in ru.netology.javaqadiplom.SavingAccountTest
[ERROR] shouldAddLessThanMaxBalance  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <5000> but was: <3000>
	at ru.netology.javaqadiplom.SavingAccountTest.shouldAddLessThanMaxBalance(SavingAccountTest.java:19)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BankTest.shouldTransferAmountMinBalance:167 expected: <5500> but was: <1000>
[ERROR]   BankTest.shouldTransferAmountOverMinBalance:148 expected: <5000> but was: <-200>
[ERROR]   BankTest.shouldTransferPositiveAmountToCreditAccount:107 expected: <2000> but was: <1000>
[ERROR]   BankTest.shouldTransferToSavingAccountMaxCreditLimit:87 expected: <8000> but was: <5000>
[ERROR]   BankTest.shouldTransferToSavingAccountOverCreditLimit:67 expected: <10000> but was: <3000>
[ERROR]   BankTest.transferPositiveAmountToSavingAccount:26 expected: <3000> but was: <-1000>
[ERROR]   SavingAccountTest.shouldAddLessThanMaxBalance:19 expected: <5000> but was: <3000>
[INFO] 
[ERROR] Tests run: 10, Failures: 7, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.129 s
[INFO] Finished at: 2023-06-06T11:13:52+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project javaqadiplom: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\Admin\Desktop\Test_first\Javaqa-team-diplom-main\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

</details>

# Окружение

* **Операционная система:** Windows 7 Профессиональная
* **IDEA:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by TatyanaKonysheva** [comment]
Тест был запущен без слияния веток, соответственно, в коде не были отражены все выполненные изменения. После слияния веток баг-репорт закрыт.

**Comment by TatyanaKonysheva** [comment]
Откорректированы шаги воспроизведения, ожидаемый и фактический результаты.
